[tool.poetry]
name = "shipyard-databricks-sql"
version = "0.1.1"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
shipyard-templates = "0.4.3a0"
databricks-sql-connector = {version = "^3.0.0", extras = ["sqlalchemy"]}
pandas = "1.5.3"
shipyard-bp-utils = "^0.1.1"

[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates", develop = true}
pytest = "^7.4.0"
python-dotenv = "^1.0.0"
black = "^23.11.0"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
