[tool.poetry]
name = "shipyard-thoughtspot"
version = "0.1.1"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"
packages = [{include = "shipyard_thoughtspot"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.0"
pandas = "1.5.3"
shipyard-templates = "^0.1.3"


[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
