[tool.poetry]
name = "shipyard-microsoft-sharepoint"
version = "0.1.0a0"
description = "A local client for working with Microsoft SharePoint"
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
shipyard-templates = "^0.9.0"
requests = "2.31"
msal = "^1.30.0"
shipyard-bp-utils = "^1.2.1"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
black = "^24.4.2"
pytest = "^8.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
