[tool.poetry]
name = "shipyard-microsoft-power-bi"
version = "0.1.2"
description = ""
authors = ["johnathan-rodriguez <johnathan.rodriguez@shipyardapp.com>"]
readme = "README.md"
packages = [{include = "shipyard_microsoft_power_bi"}]

[tool.poetry.dependencies]
python = "^3.9"
msal = "^1.26.0"
shipyard-templates = "^0.9.0"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
