[tool.poetry]
name = "shipyard-sftp"
version = "0.3.2"
description = "A local client for connecting and working with SFTP servers"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{ include = "shipyard_sftp" }]

[tool.poetry.dependencies]
python = "^3.9"
paramiko = "^3.4.0"
shipyard-bp-utils = "^1.2.0"
shipyard-templates = "^0.8.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
