[tool.poetry]
name = "shipyard-api"
version = "0.2.0"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
shipyard-templates = "^0.8.0"
shipyard-bp-utils = "^1.2.0"
pyyaml = "^6.0.1"
pandas = "^2.2.2"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
black = "^24.3.0"
pytest = "^8.1.1"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
